---
title: A small kitchen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  recipes:
    title: Recipes
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: recipe
    recipes: [
       ingredients: []
       recipe-text: ''
    ]
paginate: 10
email: hey@asmallkitchen.com
description: You found SOME FOOD.
baseurl: 
url: 
twitter_username: smallkitchen
github_username: semibad
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
