---
title: A small kitchen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  recipes:
    title: recipes
    output: true
email: hey@asmallkitchen.com
description: You found SOME FOOD.
baseurl: 
url: 
twitter_username: smallkitchen
github_username: semibad
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
defaults:
   -
      scope:
         path: ""
         type: "recipes"
      values:
         ingredients: []
         recipe-text: ""