---
title: A small kitchen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: recipe
    illustration_image
    header_image
    recipes:
    - title: ''
      header_image
      ingredients:
      - unit: ''
        item: ''
      method_text: ''
      notes: []
paginate: 10
email: hey@asmallkitchen.com
description: You found SOME FOOD.
baseurl: 
url: 
twitter_username: smallkitchen
github_username: semibad
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
