---
title: Shoulda put an egg on it
description: You found SOME FOOD.
timezone: UTC

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    intro_text: ''
    illustration_image: ''
    header_image: ''
    recipes:
    - title: ''
      header_image: ''
      ingredients:
      - unit: ''
        item: ''
      method_text: ''
      notes: []
    inspirations: []


paginate: 10
paginate_path: "/recipes/:num/"

baseurl: 
url:
permalink: pretty

email: hey@asmallkitchen.com
twitter_username: smallkitchen
github_username: semibad

markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
